services:
  - type: web
    name: eclinic-backend
    env: docker
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/Eclinic_Backend-0.0.1-SNAPSHOT.jar
    dockerfilePath: Dockerfile
